import { Language, ThemePreset } from './types';

export const TRANSLATIONS = {
  [Language.EN]: {
    title: "ElBureau",
    enterApiKey: "Gemini API Key",
    hostGame: "Host Room",
    joinGame: "Join Room",
    roomSettings: "Room Settings",
    theme: "Theme",
    customTheme: "Custom Theme...",
    difficulty: "Difficulty",
    numQuestions: "Number of Questions",
    start: "Start Game",
    generating: "Bureau Intelligence is crafting your quiz...",
    betPhase: "Bet Phase",
    betPhaseDesc: "Place your confidence chip! Once used, it's gone.",
    confidence: "Select Bet Chip",
    submitBet: "Lock In Bet",
    submitAnswer: "Submit Answer",
    questionPhase: "Question",
    waitingForOthers: "Waiting for other players...",
    revealTitle: "Let's see what everyone wrote...",
    correctAnswer: "The Correct Answer is:",
    validation: "Host Validation",
    markCorrect: "Correct",
    markWrong: "Wrong",
    nextRound: "Next Round",
    leaderboard: "Leaderboard",
    gameOver: "Game Over",
    wagerRound: "THE FINAL WAGER",
    wagerDesc: "Risk it all! Choose your points and difficulty.",
    wagerPoints: "Wager Points",
    wagerDiff: "Wager Difficulty",
    finalScore: "Final Score",
    setup: "Setup",
    hint: "Need a hint?",
    generatingFinal: "Concocting the final challenge...",
    settings: "Settings",
    close: "Close",
    save: "Save",
    language: "Language",
    apiKeyDesc: "Required to host games. Saved locally.",
    back: "Back",
    roomCode: "Room Code",
    playerName: "Player Name",
    enterRoom: "Enter Room",
    joinError: "Multiplayer features coming soon! Please Host for now.",
    pickBet: "Pick a chip!",
    thinking: "Thinking...",
    round: "Round",
    of: "of",
    revealAnswers: "Reveal Answers",
    verify: "Verify Results",
    // Advanced Settings
    advancedSettings: "Advanced Settings",
    timer: "Timer (sec)",
    allowHints: "Allow Hints",
    scoringMode: "Scoring Mode",
    scoringStandard: "Standard (0 for wrong)",
    scoringPunishing: "Punishing (-Bet for wrong)",
    qType: "Question Types",
    qTypeMixed: "Mixed",
    qTypeMC: "Multiple Choice",
    qTypeOpen: "Open Ended",
    timeInfinity: "No Timer",
  },
  [Language.FR]: {
    title: "ElBureau",
    enterApiKey: "Clé API Gemini",
    hostGame: "Créer une salle",
    joinGame: "Rejoindre",
    roomSettings: "Paramètres de la salle",
    theme: "Thème",
    customTheme: "Thème personnalisé...",
    difficulty: "Difficulté",
    numQuestions: "Nombre de questions",
    start: "Commencer",
    generating: "L'intelligence du Bureau prépare le quiz...",
    betPhase: "Phase de Mise",
    betPhaseDesc: "Choisissez votre jeton ! Une fois utilisé, il disparaît.",
    confidence: "Choisir Jeton",
    submitBet: "Valider la Mise",
    submitAnswer: "Valider la Réponse",
    questionPhase: "Question",
    waitingForOthers: "En attente des autres joueurs...",
    revealTitle: "Voyons les réponses de chacun...",
    correctAnswer: "La bonne réponse est :",
    validation: "Validation de l'hôte",
    markCorrect: "Correct",
    markWrong: "Faux",
    nextRound: "Manche suivante",
    leaderboard: "Classement",
    gameOver: "Fin de partie",
    wagerRound: "LE PARI FINAL",
    wagerDesc: "Tout ou rien ! Choisissez votre mise.",
    wagerPoints: "Points misés",
    wagerDiff: "Difficulté",
    finalScore: "Score Final",
    setup: "Configuration",
    hint: "Besoin d'un indice ?",
    generatingFinal: "Préparation du défi final...",
    settings: "Paramètres",
    close: "Fermer",
    save: "Enregistrer",
    language: "Langue",
    apiKeyDesc: "Requis pour héberger. Sauvegardé localement.",
    back: "Retour",
    roomCode: "Code de la salle",
    playerName: "Nom du joueur",
    enterRoom: "Entrer",
    joinError: "Multijoueur bientôt disponible ! Veuillez créer une partie.",
    pickBet: "Choisissez un jeton !",
    thinking: "Réfléchit...",
    round: "Manche",
    of: "sur",
    revealAnswers: "Révéler les Réponses",
    verify: "Vérifier les Résultats",
    // Advanced Settings
    advancedSettings: "Paramètres Avancés",
    timer: "Minuteur (sec)",
    allowHints: "Autoriser Indices",
    scoringMode: "Mode de Score",
    scoringStandard: "Standard (0 si faux)",
    scoringPunishing: "Punitif (-Mise si faux)",
    qType: "Types de Questions",
    qTypeMixed: "Mixte",
    qTypeMC: "Choix Multiple",
    qTypeOpen: "Question Ouverte",
    timeInfinity: "Pas de Minuteur",
  },
  [Language.AR]: {
    title: "المكتب",
    enterApiKey: "مفتاح Gemini API",
    hostGame: "إنشاء غرفة",
    joinGame: "انضمام لغرفة",
    roomSettings: "إعدادات الغرفة",
    theme: "الموضوع",
    customTheme: "موضوع مخصص...",
    difficulty: "الصعوبة",
    numQuestions: "عدد الأسئلة",
    start: "ابدأ اللعبة",
    generating: "ذكاء المكتب يقوم بإعداد الأسئلة...",
    betPhase: "مرحلة الرهان",
    betPhaseDesc: "اختر شريحة الرهان! الشريحة المستخدمة تختفي.",
    confidence: "اختر الرهان",
    submitBet: "تأكيد الرهان",
    submitAnswer: "تأكيد الإجابة",
    questionPhase: "السؤال",
    waitingForOthers: "بانتظار اللاعبين الآخرين...",
    revealTitle: "لنرى إجابات الجميع...",
    correctAnswer: "الإجابة الصحيحة هي:",
    validation: "تحقق المضيف",
    markCorrect: "صحيح",
    markWrong: "خطأ",
    nextRound: "الجولة التالية",
    leaderboard: "لوحة المتصدرين",
    gameOver: "انتهت اللعبة",
    wagerRound: "الرهان الأخير",
    wagerDesc: "خاطر بكل شيء! اختر رهان الصعوبة.",
    wagerPoints: "نقاط الرهان",
    wagerDiff: "صعوبة الرهان",
    finalScore: "النتيجة النهائية",
    setup: "إعداد",
    hint: "محتاج تلميح؟",
    generatingFinal: "جاري إعداد التحدي الأخير...",
    settings: "الإعدادات",
    close: "إغلاق",
    save: "حفظ",
    language: "اللغة",
    apiKeyDesc: "مطلوب لاستضافة الألعاب. محفوظ محلياً.",
    back: "رجوع",
    roomCode: "رمز الغرفة",
    playerName: "اسم اللاعب",
    enterRoom: "دخول",
    joinError: "اللعب الجماعي قريباً! يرجى إنشاء غرفة الآن.",
    pickBet: "اختر شريحة!",
    thinking: "يفكر...",
    round: "جولة",
    of: "من",
    revealAnswers: "كشف الإجابات",
    verify: "التحقق من النتائج",
    // Advanced Settings
    advancedSettings: "إعدادات متقدمة",
    timer: "المؤقت (ثانية)",
    allowHints: "سماح بالتلميحات",
    scoringMode: "نظام النقاط",
    scoringStandard: "قياسي (0 للخطأ)",
    scoringPunishing: "عقابي (-الرهان للخطأ)",
    qType: "أنواع الأسئلة",
    qTypeMixed: "مختلط",
    qTypeMC: "خيارات متعددة",
    qTypeOpen: "مفتوح",
    timeInfinity: "بدون مؤقت",
  },
};

export const THEME_PRESETS: ThemePreset[] = [
  { id: 'general', label: { en: 'General Knowledge', fr: 'Culture Générale', ar: 'معلومات عامة' }, value: 'General Knowledge' },
  { id: 'movies', label: { en: 'Movies & TV', fr: 'Cinéma & TV', ar: 'أفلام وتلفزيون' }, value: 'Movies and TV Shows' },
  { id: 'science', label: { en: 'Science & Nature', fr: 'Sciences & Nature', ar: 'علوم وطبيعة' }, value: 'Science and Nature' },
  { id: 'history', label: { en: 'History', fr: 'Histoire', ar: 'تاريخ' }, value: 'History' },
  { id: 'pop', label: { en: 'Pop Culture', fr: 'Pop Culture', ar: 'ثقافة شعبية' }, value: 'Pop Culture' },
];

export const AVATAR_COLORS = [
  'bg-pop-blue',
  'bg-pop-red',
  'bg-pop-yellow',
  'bg-pop-green',
];